# Generated by Django 2.0.2 on 2018-03-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('organizer', '0003_startup_data'),
    ]

    operations = [
    ]
