# Generated by Django 2.0.2 on 2018-03-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_newslink_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newslink',
            unique_together=set({('slug', 'startup')}),
        ),
    ]
